/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:dd489938-b38f-4ab6-a953-2d013c29beef",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_DfIDqdRQi",
    "aws_user_pools_web_client_id": "4fo0t3use3hjtknph6v5169l7c",
    "oauth": {},
    "aws_user_files_s3_bucket": "mymedia-dev-output-8se39g3r145558-dev",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
